USE [MuckScraperDb]
GO
/****** Object:  Database [MuckScraperDb]    Script Date: 4/11/2021 8:53:12 PM ******/
CREATE DATABASE [MuckScraperDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MuckScraperDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MuckScraperDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MuckScraperDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MuckScraperDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MuckScraperDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MuckScraperDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MuckScraperDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MuckScraperDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MuckScraperDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MuckScraperDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MuckScraperDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [MuckScraperDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MuckScraperDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MuckScraperDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MuckScraperDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MuckScraperDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MuckScraperDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MuckScraperDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MuckScraperDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MuckScraperDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MuckScraperDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MuckScraperDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MuckScraperDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MuckScraperDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MuckScraperDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MuckScraperDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MuckScraperDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [MuckScraperDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MuckScraperDb] SET RECOVERY FULL 
GO
ALTER DATABASE [MuckScraperDb] SET  MULTI_USER 
GO
ALTER DATABASE [MuckScraperDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MuckScraperDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MuckScraperDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MuckScraperDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MuckScraperDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MuckScraperDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MuckScraperDb', N'ON'
GO
ALTER DATABASE [MuckScraperDb] SET QUERY_STORE = OFF
GO
USE [MuckScraperDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 4/11/2021 8:53:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Articles]    Script Date: 4/11/2021 8:53:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Articles](
	[ArticleId] [uniqueidentifier] NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[SourceMedium] [nvarchar](max) NULL,
	[AuthorFirstName] [nvarchar](max) NULL,
	[AuthorLastName] [nvarchar](max) NULL,
	[SourceUrl] [nvarchar](max) NULL,
	[PublicationName] [nvarchar](max) NULL,
	[UploadDate] [datetime2](7) NOT NULL,
	[PublishDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Articles] PRIMARY KEY CLUSTERED 
(
	[ArticleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profiles]    Script Date: 4/11/2021 8:53:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profiles](
	[ProfileId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[MiddleName] [nvarchar](max) NULL,
	[Photo] [varbinary](max) NULL,
 CONSTRAINT [PK_Profiles] PRIMARY KEY CLUSTERED 
(
	[ProfileId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 4/11/2021 8:53:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[RegistrationDate] [datetime2](7) NOT NULL,
	[LastLoginDate] [datetime2](7) NOT NULL,
	[Credentials] [tinyint] NOT NULL,
	[PrimaryEmail] [nvarchar](max) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [MuckScraperDb] SET  READ_WRITE 
GO
